<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.taybct</groupId>
        <artifactId>spring-taybct-example</artifactId>
        <version>3.5.1.1</version>
    </parent>

    <artifactId>exp-elk</artifactId>
    <name>${project.artifactId}</name>
    <packaging>jar</packaging>
    <description>elasticsearch 搜索引擎</description>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <maven.compiler.release>21</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>

        <!--启动模块-->
        <dependency>
            <groupId>io.github.taybct</groupId>
            <artifactId>spring-taybct-tool-launch</artifactId>
        </dependency>
        <!--微服务依赖-->
        <dependency>
            <groupId>io.github.taybct</groupId>
            <artifactId>spring-taybct-tool-cloud</artifactId>
        </dependency>

        <dependency>
            <groupId>io.github.taybct</groupId>
            <artifactId>spring-taybct-tool-core</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!--spring web-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>${spring-boot.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-undertow</artifactId>
            <version>${spring-boot.version}</version>
        </dependency>

        <!--es 操作-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-elasticsearch</artifactId>
            <version>${spring-boot.version}</version>
        </dependency>

    </dependencies>

</project>